version: '3.8'
services:
  pokedex:
    build:
      context: .
      dockerfile: Dockerfile
    image: pokedex
    volumes:
      - .:/src
    command: nodemon npm run start
    restart: unless-stopped
    ports:
      - "7000:7000"
    env_file: environments/.env-sample